version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      - checkout
      - run: sudo apt-get update -y  && sudo apt-get install nodejs -y

      - run:
          name: cloning github
          command: git clone https://github.com/hajilok/youtube-live-streaming && cd youtube-live-streaming 
      
      - run:
          name: Install Node.js dependencies
          command: npm install
      
      # Store .env file
      - run:
          name: Store .env file
          command: echo 'streamkey=8sdp-6tr1-ca0t-0xvx-fgj3' > .env

      # Run your Node.js app
      - run:
          name: Run Your Node.js App
          command: node main.js  # Replace with your Node.js application's entry point


workflows:
  version: 2
  build-deploy:
    jobs:
      - build

